Peer Review
alain-kubwayo/medical-core-clone pull request #7
Opened 2022-09-17 09:41 UTC by alain-kubwayo

2022-09-17 14:24 UTC, IbrahimBagalwa reviewed
congratilations my dear! you have respected the rules of bem very well. keep it up. try to implament this comment i think it will be good. Thanks

2022-09-17 14:24 UTC, IbrahimBagalwa commented on index.html
> +                    <a class="header__login-link" href="#">Login</a>
Think the LOGIN link will have the same name with the lLEARN MORE btn. If you follow the figma link you can notice it.

2022-09-17 14:24 UTC, IbrahimBagalwa commented on index.html
> +                    <p class="footer__text">Problems trying to resolve the conflict between <br>
this footer__text should be like man__text but in footer text you add only the modifier because the footer text is center.

2022-09-19 06:26 UTC, NNesta requested changes

2022-09-19 06:26 UTC, NNesta commented on index.css
> +}
You should have created card block because it is a standalone and reusable component instead of making an element

2022-09-19 07:55 UTC, NNesta requested changes

2022-09-19 07:56 UTC, alain-kubwayo commented on index.html
> +                    <div class="cards__card">
Alright, working on that right away, thanks.

2022-09-19 09:12 UTC, alain-kubwayo commented on index.html
> +                    <a class="header__login-link" href="#">Login</a>
Oh okay, working on it.

2022-09-19 09:49 UTC, NNesta approved these changes
Nice work @alain-kubwayo

2022-09-19 09:57 UTC, IbrahimBagalwa approved these changes
Great job man keep it up :)

2022-09-19 22:26 UTC, Morrism1 requested changes

2022-09-19 22:26 UTC, Morrism1 commented on index.html
> +                        <span>JOIN US</span>
`span` element with no class is not necessary in BEM convention.

2022-09-19 22:26 UTC, Morrism1 commented on index.html
> +                        <span>Learn More</span>
`span` element with no class is not necessary in BEM convention.

2022-09-19 22:26 UTC, Morrism1 commented on index.html
> +                        <div>
`div` element with no class is not necessary in BEM convention.

2022-09-19 22:26 UTC, Morrism1 commented on index.html
> +                        <div>
`div` element with no class is not necessary in BEM convention.

2022-09-19 22:26 UTC, Morrism1 commented on index.html
> +                        <div>
`div` element with no class is not necessary in BEM convention.

2022-09-19 22:26 UTC, Morrism1 commented on index.html
> +                        <div>
`div` element with no class is not necessary in BEM convention.

2022-09-19 22:26 UTC, Morrism1 commented on index.html
> +                    <p class="main__text">Problems trying to resolve the conflict between <br>
Here we have `main__text` which means I expect this element to be in a BLOCK called `main` but that's not the case.

2022-09-21 06:39 UTC, IbrahimBagalwa approved these changes
## Great job
keep it up bro you apply all request change :)

2022-09-21 08:41 UTC, NNesta approved these changes
Nice work @alain-kubwayo

2022-09-21 12:52 UTC, Morrism1 approved these changes
Good Job @alain-kubwayo!

2022-09-22 10:44 UTC, merged